spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
  application:
    name: restful-service
  messages:
    basename: messages

  security:
    user:
      name: jangdm37
      password: abcd1234

server:
  port: 8088

logging:
  level:
    org.springframework: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
